version: '3.4'

services:
 
  # Logging
  elasticsearch:
    restart: always
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    restart: always
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "8080:8080"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  kibana:
    restart: always
    volumes:
      - ./elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  #data
  eventstore:
    restart: always
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes: 
      - type: volume
        source: esdata
        target: /var/lib/eventstore
        read_only: false
      - type: volume
        source: eslog
        target: /var/log/eventstore
        read_only: false      

  #it-ops
  healthmonitor:
    restart: always
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Identity server health check
      - HealthChecksUI__HealthChecks__0__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Adminportal health check
      - HealthChecksUI__HealthChecks__1__Uri=http://adminportal/hc
      - HealthChecksUI__HealthChecks__2__Name=Identity clienthub health check
      - HealthChecksUI__HealthChecks__2__Uri=http://identityaccess-clienthub/hc
      - HealthChecksUI__HealthChecks__3__Name=Email sender health check
      - HealthChecksUI__HealthChecks__3__Uri=http://identityaccess-emailsender/hc
      - HealthChecksUI__HealthChecks__4__Name=Collaboration health check
      - HealthChecksUI__HealthChecks__4__Uri=http://collaboration-api/hc
      - HealthChecksUI__HealthChecks__5__Name=Projectmanagement health check
      - HealthChecksUI__HealthChecks__5__Uri=http://projectmanagement-api/hc
      - HealthChecksUI__HealthChecks__6__Name=policyserver health check
      - HealthChecksUI__HealthChecks__6__Uri=http://policyserver/hc
      - HealthChecksUI__HealthChecks__7__Name=policyserver manager health check
      - HealthChecksUI__HealthChecks__7__Uri=http://policyserver-manager-api/hc
      - HealthChecksUI__HealthChecks__8__Name=policyserver-manager userselector health check
      - HealthChecksUI__HealthChecks__8__Uri=http://policyserver-manager-userselector-api/hc
      - HealthChecksUI__HealthChecks__9__Name=reporting health check
      - HealthChecksUI__HealthChecks__9__Uri=http://planning-reporting-api/hc
      - HealthChecksUI__HealthChecks__10__Name=reporting clienthub health check
      - HealthChecksUI__HealthChecks__10__Uri=http://planning-reporting-clienthub/hc
      - HealthChecksUI__HealthChecks__11__Name=accounting-api health check
      - HealthChecksUI__HealthChecks__11__Uri=http://accounting-api/hc
      - HealthChecksUI__HealthChecks__12__Name=accounting capacitydispatcher health check
      - HealthChecksUI__HealthChecks__12__Uri=http://accounting-capacitydispatcher/hc
      - HealthChecksUI__HealthChecks__13__Name=accounting integration health check
      - HealthChecksUI__HealthChecks__13__Uri=http://accounting-integration/hc
      - HealthChecksUI__HealthChecks__14__Name=salesorders-api health check
      - HealthChecksUI__HealthChecks__14__Uri=http://salesorders-api/hc
      - HealthChecksUI__HealthChecks__15__Name=salesorders-integration health check
      - HealthChecksUI__HealthChecks__15__Uri=http://salesorders-integration/hc
      - HealthChecksUI__HealthChecks__16__Name=salesorders health check
      - HealthChecksUI__HealthChecks__16__Uri=http://salesorders/hc
      - HealthChecksUI__HealthChecks__17__Name=planning-capacityutilization-api health check
      - HealthChecksUI__HealthChecks__17__Uri=http://planning-capacityutilization-api/hc
      - HealthChecksUI__HealthChecks__18__Name=planning-typecurve-api health check
      - HealthChecksUI__HealthChecks__18__Uri=http://planning-typecurve-api/hc    
      - HealthChecksUI__HealthChecks__19__Name=wage-data-api health check
      - HealthChecksUI__HealthChecks__19__Uri=http://wage-data-api/hc   
      - HealthChecksUI__HealthChecks__20__Name=bill of material health check
      - HealthChecksUI__HealthChecks__20__Uri=http://bom-api/hc  
        #destkopclient bff
      - HealthChecksUI__HealthChecks__101__Name=desktopprojectplanningcomposition health check
      - HealthChecksUI__HealthChecks__101__Uri=http://desktopprojectplanningcomposition/hc
      - HealthChecksUI__HealthChecks__102__Name=clienthub health check
      - HealthChecksUI__HealthChecks__102__Uri=http://clienthub/hc
  
  # help
  ams-help:
    restart: always
    ports: 
        - "8888:3030"
    environment:
        - NODE_ENV=production
    volumes:
        - type: volume
          source: helpdata
          target: /app/public/content
          read_only: false
    working_dir: /app
    command: bash -c "cp -r /usr/share/app/content/ /app/public/ && npm start"

  # authorization
  policyserver:
    restart: always
    ports:
      - "7611:80"
    environment:
      - ConnectionStrings__ams=${AMS_DB}
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB}
       
  policyserver-manager-api:
    restart: always
    ports:
      - "7612:80"
    environment:
      - ConnectionStrings__ams=${AMS_DB}
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB}
      - CultureCode=${CULTURE_CODE:-de-DE}
      
  policyserver-manager-userselector-api:
    restart: always
    ports:
      - "7613:80"
    environment:
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB}

  #project management
  projectmanagement-api:
    restart: always
    ports:
      - "7601:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - IdentityServerUrl=http://identity-api
      - ConnectionStrings__ProjectManagement=${AMS_DB}

  projectmanagement:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}
      - CultureCode=${CULTURE_CODE:-de-DE}

  projectmanagement-readmodelgenerator:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}
      - ConnectionStrings__EventStore=${EVENTSTORE_DB:-tcp://admin:changeit@eventstore:1113}

  #collaboration
  collaboration-api:
    restart: always
    ports:
      - "7602:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}
  
  planning-capacityutilization-api:
    restart: always
    ports:
      - "7606:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__ams=${AMS_DB}
    
  planning-typecurve-api:
    restart: always
    ports:
      - "7607:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__ams=${AMS_DB}
    
  wage-data-api:
    restart: always
    ports:
      - "7609:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__ams=${AMS_DB}
    
  #accounting  
  accounting-api:
    restart: always
    ports:
      - "7603:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}

  projecttracking-clienthub:
    restart: always
    ports:
      - "7604:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}

  accounting-capacitydispatcher:
   restart: always
   ports:
     - "5004:80"
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://0.0.0.0:80    
     - ConnectionStrings__ams=${AMS_DB}

  accounting-integration:
    restart: always
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}

  #sales orders
  salesorders-api:
    restart: always
    ports:
      - "7605:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}

  salesorders-integration:
    restart: always
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}
      - CultureCode=${CULTURE_CODE:-de-DE}

  salesorders:
    restart: always
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}

  #reporting (multiproject)
  planning-reporting-api:
    restart: always
    ports:
      - "7608:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__ams=${AMS_DB}

  planning-reporting-clienthub:
    restart: always
    ports:
      - "7900:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__ams=${AMS_DB}

  #production planning
  bom-api:
    restart: always
    ports:
      - "7618:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}

  #identity access
  identity-api:
    restart: always
    ports:
      - "7614:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB}
      - CultureCode=${CULTURE_CODE:-de-DE}
      - IdentityServerUrl=http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:7614
      - AdminPortalUrl=http://adminportal
    volumes:
      - type: bind
        source: ./profileImages
        target: /app/wwwroot/picture
        read_only: false

  adminportal:
    restart: always
    ports:
      - "7615:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80 
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB}
      - CultureCode=${CULTURE_CODE:-de-DE}
      - IdentityServerUrl=http://identity-api                  

  identityaccess-clienthub:
    restart: always
    ports:
      - "7616:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB}
            
  identityaccess-emailsender:
    restart: always
    ports:
      - "7617:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB}
      - CultureCode=${CULTURE_CODE} 
      - EmailSettings__MailServer=${MAIL_SERVER}
      - EmailSettings__Port=${MAIL_PORT}
      - EmailSettings__SenderName=${MAIL_SENDER_NAME}
      - EmailSettings__Sender=${MAIL_SENDER}
      - EmailSettings__Password=${MAIL_PASSWORD}
      - EmailSettings__IsAuthenticationRequired=${MAIL_IS_AUTHENTICATION_REQUIRED}

  #bff
  desktopprojectplanningcomposition:
    restart: always
    ports:
      - "7701:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - Urls__ProjectManagement=http://projectmanagement-api
      - Urls__SalesOrders=http://salesorders-api 
  
  desktopschedulingapigw:
    restart: always
    volumes:
      - ./Envoy/config/desktopscheduling:/etc/envoy
    ports:
      - "5200:80"
      - "15200:8001"
      - "10000:10000"

  clienthub:
    restart: always
    ports:
      - "7800:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB}
            
volumes:
  esdata:
  eslog:     
  helpdata:
  elasticsearch-data: