version: '3.4'

services:   
  eventstore:
    image: eventstore/eventstore:release-5.0.8

  #it-ops
  healthmonitor:
    image: ${REGISTRY:-amssolution}/itops.healthmonitor:${PLATFORM:-linux}-${TAG:-latest}

  #help
  ams-help:
    image: ${REGISTRY:-amssolution}/ams.help:${PLATFORM:-linux}-${TAG:-latest}

  #authorization
  policyserver:
    image: ${REGISTRY:-amssolution}/policyserver:${PLATFORM:-linux}-${TAG:-latest}

  policyserver-manager-api:
     image: ${REGISTRY:-amssolution}/policyserver.manager.api:${PLATFORM:-linux}-${TAG:-latest}
        
  policyserver-manager-userselector-api:
    image: ${REGISTRY:-amssolution}/policyserver.manager.userselector.api:${PLATFORM:-linux}-${TAG:-latest}  

  #project management
  projectmanagement-api:
    image: amssolution/projectmanagement.api:${PLATFORM:-linux}-${TAG:-latest}

  projectmanagement:
    image: ${REGISTRY:-amssolution}/projectmanagement:${PLATFORM:-linux}-${TAG:-latest}

  projectmanagement-readmodelgenerator:
    image: ${REGISTRY:-amssolution}/projectmanagement.readmodelgenerator:${PLATFORM:-linux}-${TAG:-latest}

  #collaboration
  collaboration-api:
    image: amssolution/collaboration.api:${PLATFORM:-linux}-${TAG:-latest}

  planning-capacityutilization-api:
    image: ${REGISTRY:-amssolution}/planning.capacityutilization.api:${PLATFORM:-linux}-${TAG:-latest}
  
  planning-typecurve-api:
    image: ${REGISTRY:-amssolution}/planning-typecurve-api:${PLATFORM:-linux}-${TAG:-latest}
  
  wage-data-api:
    image: ${REGISTRY:-amssolution}/wage.data.api:${PLATFORM:-linux}-${TAG:-latest}
  
  #accounting
  accounting-api:
    image: amssolution/accounting.api:${PLATFORM:-linux}-${TAG:-latest}

  projecttracking-clienthub:
    image: ${REGISTRY:-amssolution}/projecttracking.clienthub:${PLATFORM:-linux}-${TAG:-latest}

  accounting-capacitydispatcher:
   image: ${REGISTRY:-amssolution}/accounting.resourcecapacitydispatcher:${PLATFORM:-linux}-${TAG:-latest}

  accounting-integration:
    image: ${REGISTRY:-amssolution}/accounting.integration:${PLATFORM:-linux}-${TAG:-latest}

  #sales orders
  salesorders-api:
    image: ${REGISTRY:-amssolution}/salesorders.api:${PLATFORM:-linux}-${TAG:-latest}

  salesorders-integration:
    image: ${REGISTRY:-amssolution}/salesorders.integration:${PLATFORM:-linux}-${TAG:-latest}

  salesorders:
    image: ${REGISTRY:-amssolution}/salesorders:${PLATFORM:-linux}-${TAG:-latest}

  #capacityutilization-api:
  #  image: amssolution/planning.capacityutilization.api:${PLATFORM:-linux}-${TAG:-latest}
    
  #reporting (multiproject)
  planning-reporting-api:
     image: ${REGISTRY:-amssolution}/scheduling.reporting.api:${PLATFORM:-linux}-${TAG:-latest}
     
  planning-reporting-clienthub:
      image: ${REGISTRY:-amssolution}/scheduling.reporting.clienthub:${PLATFORM:-linux}-${TAG:-latest}

  #production planning
  bom-api:
    image: ${REGISTRY:-amssolution}/productionplanning.bom.api:${PLATFORM:-linux}-${TAG:-latest}

  #identity access
  identity-api:
    image: ${REGISTRY:-amssolution}/identityaccess.identityserver:${PLATFORM:-linux}-${TAG:-latest}
         
  adminportal:
    image: ${REGISTRY:-amssolution}/identityaccess.adminportal:${PLATFORM:-linux}-${TAG:-latest}

  identityaccess-clienthub:
    image: ${REGISTRY:-amssolution}/identityaccess.clienthub:${PLATFORM:-linux}-${TAG:-latest}
            
  identityaccess-emailsender:
    image: ${REGISTRY:-amssolution}/identityaccess.emailsender:${PLATFORM:-linux}-${TAG:-latest}

  #bff
  desktopschedulingapigw:
    image: envoyproxy/envoy:v1.11.1

  desktopprojectplanningcomposition:
    image: ${REGISTRY:-amssolution}/desktop.projectplanning.compositiongateway:${PLATFORM:-linux}-${TAG:-latest}

  clienthub:
    image: ${REGISTRY:-amssolution}/itops.clienthub:${PLATFORM:-linux}-${TAG:-latest}
