version: "3.4"

services:
    project.eventstore:
        image: eventstore/eventstore:release-5.0.8
        networks: 
            - project
        ports:
            - "2113:2113"
            - "1113:1113"
        restart: always
        volumes: 
            - type: volume
              source: esdata
              target: /var/lib/eventstore
              read_only: false
            - type: volume
              source: eslog
              target: /var/log/eventstore
              read_only: false

    identityaccess.identityserver:
        image: ${PROJECT_IMAGE_ROOT}/identityaccess.identityserver:${TAG}
        networks: 
            - project
        ports:
            - "7614:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always
                    
    identityaccess.adminportal:
        image: ${PROJECT_IMAGE_ROOT}/identityaccess.adminportal:${TAG}
        networks: 
            - project
        ports:
            - "7615:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    accounting.api:
        image: ${PROJECT_IMAGE_ROOT}/accounting.api:${TAG}
        networks: 
            - project
        ports:
            - "7603:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    accounting.resourcecapacitydispatcher:
        image: ${PROJECT_IMAGE_ROOT}/accounting.resourcecapacitydispatcher:${TAG}
        networks: 
            - project
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    collaboration.api:
        image: ${PROJECT_IMAGE_ROOT}/collaboration.api:${TAG}
        networks: 
            - project
        ports:
            - "7602:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    itops.clienthub:
        image: ${PROJECT_IMAGE_ROOT}/itops.clienthub:${TAG}
        networks: 
            - project
        ports:
            - "7800:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    itops.compositiongateway:
        image: ${PROJECT_IMAGE_ROOT}/itops.compositiongateway:${TAG}
        networks: 
            - project
        ports:
            - "7700:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    planning.capacityutilization.api:
        image: ${PROJECT_IMAGE_ROOT}/planning.capacityutilization.api:${TAG}
        networks: 
            - project
        ports:
            - "7606:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    planning.reporting.api:
        image: ${PROJECT_IMAGE_ROOT}/planning.reporting.api:${TAG}
        networks: 
            - project
        ports:
            - "7608:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    planning.reporting.clienthub:
        image: ${PROJECT_IMAGE_ROOT}/planning.reporting.clienthub:${TAG}
        networks: 
            - project
        ports:
            - "7900:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    planning.tracking.clienthub:
        image: ${PROJECT_IMAGE_ROOT}/planning.tracking.clienthub:${TAG}
        networks: 
            - project
        ports:
            - "7604:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    planning.typecurve.api:
        image: ${PROJECT_IMAGE_ROOT}/planning.typecurve.api:${TAG}
        networks: 
            - project
        ports:
            - "7607:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    projectmanagement:
        image: ${PROJECT_IMAGE_ROOT}/projectmanagement:${TAG}
        networks: 
            - project
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    projectmanagement.api:
        image: ${PROJECT_IMAGE_ROOT}/projectmanagement.api:${TAG}
        networks: 
            - project
        ports:
            - "7601:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    projectmanagement.readmodelgenerator:
        image: ${PROJECT_IMAGE_ROOT}/projectmanagement.readmodelgenerator:${TAG}
        networks: 
            - project
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    sales.orderplanningintegration:
        image: ${PROJECT_IMAGE_ROOT}/sales.orderplanningintegration:${TAG}
        networks: 
            - project
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    sales.salesorders:
        image: ${PROJECT_IMAGE_ROOT}/sales.salesorders:${TAG}
        networks: 
            - project
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    sales.salesorders.api:
        image: ${PROJECT_IMAGE_ROOT}/sales.salesorders.api:${TAG}
        networks: 
            - project
        ports:
            - "7605:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    wage.wagedata.api:
        image: ${PROJECT_IMAGE_ROOT}/wage.wagedata.api:${TAG}
        networks: 
            - project
        ports:
            - "7609:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    policyserver:
        image: ${PROJECT_IMAGE_ROOT}/policyserver:${TAG}
        networks: 
            - project
        ports:
            - "7611:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    policyserver.manager.api:
        image: ${PROJECT_IMAGE_ROOT}/policyserver.manager.api:${TAG}
        networks: 
            - project
        ports:
            - "7612:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

    policyserver.manager.userselector.api:
        image: ${PROJECT_IMAGE_ROOT}/policyserver.manager.userselector.api:${TAG}
        networks: 
            - project
        ports:
            - "7613:80"
        environment: 
            CONSUL_URL: ${CONSUL_URL}
            ENVIRONMENT_NAME: ${ENVIRONMENT_NAME}
        restart: always

volumes:
    esdata:
    eslog:
    