version: '3.4'
services:
    portainer:
        image: portainer/portainer-ce:latest
        networks: 
            - project        
        ports:
            - "8000:8000"
            - "9000:9000"
        restart: always
        volumes: 
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              read_only: false
            - type: volume
              source: portainerdata
              target: /data
              read_only: false
              
    consul:
        image: consul:latest
        networks: 
            - project
        restart: always
        ports: 
            - "8500:8500"
            - "8600:8600/udp"
        command: sh -c "consul agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0"    

    env:
        image: devth/git2consul:latest
        networks: 
            - project        
        restart: always
        volumes:
          - ./git2consul/git2consul.json:/opt/git2consul/git2consul.json
          - type: bind
            source: "./config"
            target: "/repo"
            read_only: false
        command: "--endpoint consul --config-file /opt/git2consul/git2consul.json"
        depends_on: 
          - consul 

volumes:
  consuldata:
  portainerdata:

networks:
  project:
