version: '3.4'

services:
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes: 
      - type: volume
        source: esdata
        target: /var/lib/eventstore
        read_only: false
      - type: volume
        source: eslog
        target: /var/log/eventstore
        read_only: false      

  #it-ops
  healthmonitor:
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Identity server health check
      - HealthChecksUI__HealthChecks__0__Uri=http://identity-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Adminportal health check
      - HealthChecksUI__HealthChecks__1__Uri=http://adminportal/hc
      - HealthChecksUI__HealthChecks__2__Name=Identity clienthub health check
      - HealthChecksUI__HealthChecks__2__Uri=http://identityaccess-clienthub/hc
      - HealthChecksUI__HealthChecks__3__Name=Email sender health check
      - HealthChecksUI__HealthChecks__3__Uri=http://identityaccess-emailsender/hc
      - HealthChecksUI__HealthChecks__4__Name=Collaboration health check
      - HealthChecksUI__HealthChecks__4__Uri=http://collaboration-api/hc
      - HealthChecksUI__HealthChecks__5__Name=Projectmanagement health check
      - HealthChecksUI__HealthChecks__5__Uri=http://projectmanagement-api/hc
      - HealthChecksUI__HealthChecks__6__Name=policyserver health check
      - HealthChecksUI__HealthChecks__6__Uri=http://policyserver/hc
      - HealthChecksUI__HealthChecks__7__Name=policyserver manager health check
      - HealthChecksUI__HealthChecks__7__Uri=http://policyserver-manager-api/hc
      - HealthChecksUI__HealthChecks__8__Name=policyserver-manager userselector health check
      - HealthChecksUI__HealthChecks__8__Uri=http://policyserver-manager-userselector-api/hc
      - HealthChecksUI__HealthChecks__9__Name=reporting health check
      - HealthChecksUI__HealthChecks__9__Uri=http://planning-reporting-api/hc
      - HealthChecksUI__HealthChecks__10__Name=reporting clienthub health check
      - HealthChecksUI__HealthChecks__10__Uri=http://planning-reporting-clienthub/hc
      - HealthChecksUI__HealthChecks__11__Name=accounting-api health check
      - HealthChecksUI__HealthChecks__11__Uri=http://accounting-api/hc
      - HealthChecksUI__HealthChecks__12__Name=accounting capacitydispatcher health check
      - HealthChecksUI__HealthChecks__12__Uri=http://accounting-capacitydispatcher/hc
      - HealthChecksUI__HealthChecks__13__Name=accounting integration health check
      - HealthChecksUI__HealthChecks__13__Uri=http://accounting-integration/hc
      - HealthChecksUI__HealthChecks__14__Name=salesorders-api health check
      - HealthChecksUI__HealthChecks__14__Uri=http://salesorders-api/hc
      - HealthChecksUI__HealthChecks__15__Name=salesorders-integration health check
      - HealthChecksUI__HealthChecks__15__Uri=http://salesorders-integration/hc
      - HealthChecksUI__HealthChecks__16__Name=salesorders health check
      - HealthChecksUI__HealthChecks__16__Uri=http://salesorders/hc
       #destkopclient bff
      - HealthChecksUI__HealthChecks__101__Name=desktopprojectplanningcomposition health check
      - HealthChecksUI__HealthChecks__101__Uri=http://desktopprojectplanningcomposition/hc
      - HealthChecksUI__HealthChecks__102__Name=clienthub health check
      - HealthChecksUI__HealthChecks__102__Uri=http://clienthub/hc

  # authorization
  policyserver:
    ports:
      - "7611:80"
    environment:
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB:-Server=sqldata;Database=identity;User Id=sa;Password=Pass@word}
       
  policyserver-manager-api:
    ports:
      - "7612:80"
    environment:
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}      
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB:-Server=sqldata;Database=identity;User Id=sa;Password=Pass@word}
      - CultureCode=${CULTURE_CODE:-de-DE}
      
  policyserver-manager-userselector-api:
    ports:
      - "7613:80"
    environment:
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB:-Server=sqldata;Database=identity;User Id=sa;Password=Pass@word}

  #project management
  projectmanagement-api:
    ports:
      - "7601:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - IdentityServerUrl=http://identity-api
      - ConnectionStrings__ProjectManagement=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  projectmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}
      - CultureCode=${CULTURE_CODE:-de-DE}

  projectmanagement-readmodelgenerator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}
      - ConnectionStrings__EventStore=${EVENTSTORE_DB:-tcp://admin:changeit@eventstore:1113}

  #collaboration
  collaboration-api:
    ports:
      - "7602:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}
  
  #accounting  
  accounting-api:
    ports:
      - "7603:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  projecttracking-clienthub:
    ports:
      - "7604:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  #accounting-capacitydispatcher:
  #  ports:
  #    - "5004:80"
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://0.0.0.0:80    
  #    - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  accounting-integration:
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  #sales orders
  salesorders-api:
    ports:
      - "7605:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  salesorders-integration:
   ports:
     - "5003:80"
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://0.0.0.0:80    
     - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}
     - CultureCode=${CULTURE_CODE:-de-DE}

  salesorders:
   ports:
     - "5002:80"
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://0.0.0.0:80    
     - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  #reporting (multiproject)
  planning-reporting-api:
        ports:
            - "7608:80"
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - ASPNETCORE_URLS=http://0.0.0.0:80
           - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  planning-reporting-clienthub:
        ports:
            - "7900:80"
        environment:
           - ASPNETCORE_ENVIRONMENT=Development
           - ASPNETCORE_URLS=http://0.0.0.0:80
           - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}

  #identity access
  identity-api:
    ports:
      - "7614:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB:-Server=sqldata;Database=identity;User Id=sa;Password=Pass@word}
      - CultureCode=${CULTURE_CODE:-de-DE}
      - IdentityServerUrl=http://${AMS_PROJECT_EXTERNAL_DNS_NAME_OR_IP}:7614
      - AdminPortalUrl=http://adminportal
    volumes:
      - type: bind
        source: ./profileImages
        target: /app/wwwroot/picture
        read_only: false

  adminportal:
    ports:
      - "7615:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80 
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB:-Server=sqldata;Database=identity;User Id=sa;Password=Pass@word}
      - CultureCode=${CULTURE_CODE:-de-DE}
      - IdentityServerUrl=http://identity-api                  

  identityaccess-clienthub:
    ports:
      - "7616:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB:-Server=sqldata;Database=identity;User Id=sa;Password=Pass@word}
            
  identityaccess-emailsender:
    ports:
      - "7617:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__IdentityAccess=${IDENTITY_ACCESS_DB:-Server=sqldata;Database=identity;User Id=sa;Password=Pass@word}
      - CultureCode=${CULTURE_CODE} 
      - EmailSettings__MailServer=${MAIL_SERVER}
      - EmailSettings__Port=${MAIL_PORT}
      - EmailSettings__SenderName=${MAIL_SENDER_NAME}
      - EmailSettings__Sender=${MAIL_SENDER}
      - EmailSettings__Password=${MAIL_PASSWORD}
      - EmailSettings__IsAuthenticationRequired=${MAIL_IS_AUTHENTICATION_REQUIRED}

  #bff
  desktopprojectplanningcomposition:
    ports:
      - "7701:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - Urls__ProjectManagement=http://projectmanagement-api
      - Urls__SalesOrders=http://salesorders-api 
  
  desktopschedulingapigw:
    volumes:
      - ./ApiGateways/Envoy/config/desktopscheduling:/etc/envoy
    ports:
      - "5200:80"
      - "15200:8001"
      - "10000:10000"

  clienthub:
    ports:
      - "7800:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80    
      - ConnectionStrings__ams=${AMS_DB:-Server=sqldev2012.ams.local,1433;Database=dev-amsprojekt;User ID=projectuser;Password=projectuser;Max Pool Size=100}
            
volumes:
  esdata:
  eslog:     