version: '3.4'

services:      
  eventstore:
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes: 
      - type: volume
        source: esdata
        target: /var/lib/eventstore
        read_only: false
      - type: volume
        source: eslog
        target: /var/log/eventstore
        read_only: false      

volumes:
  esdata:
  eslog:         
